services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CORS_ORIGINS: "*"
    restart: always

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
